### ISSUE TITLE
pipeline not work

### ISSUE THREAD

**Issue by mitnk** [xonsh/slug#10] opened 2017-03-18 08:37 UTC
Content of file `test_slug.py`:

```
from slug import Process, ProcessGroup, Pipe

with ProcessGroup() as pg:
  pipe = Pipe()
  spam = pg.add(Process(['ls'], stdout=pipe.side_in))
  eggs = pg.add(Process(['wc'], stdin=pipe.side_out))
pg.start()
pg.join()
```

Run `py test_slug.py`, on Linux, it will stuck. On Mac this issue shows:
```
$ py test_slug.py
Traceback (most recent call last):
  File "test_slug.py", line 8, in <module>
    pg.start()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh_slug-0.0.1-py3.6.egg/slug/posix.py", line 91, in start
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/xonsh_slug-0.0.1-py3.6.egg/slug/posix.py", line 63, in pgid
ProcessLookupError: [Errno 3] No such process
      71      72     750
```

**Comment by AstraLuma** [comment] 2017-03-18 19:58
Oh, that's... huh.

Yup, that's a bug.

**Comment by AstraLuma** [comment] 2017-03-18 20:07
You need to close your copies of the Pipe sides after the processes have started. (slug doesn't handle this in cases where, say, you're passing a PTY to 3 programs or whatever.)

**Comment by ghost** [comment] 2017-03-18 20:22
@astronouth7303  anything to do with what python docs state [here](https://docs.python.org/3/library/subprocess.html#replacing-shell-pipeline) ?

do we follow this on xonsh ? didn't find anything from a quick search
maybe we should do this on slug when exiting the contextmanager?

**Comment by AstraLuma** [comment] 2017-03-18 20:37
@laerus It has to happen after the processes are actually started (and therefore have their own copies).

The problem is that while it's probably what we want to do with Pipes, files or sockets, it's almost certainly wrong for explicit stdin/out/err (ie, passing `sys.stdin`), and sometimes wrong for Psuedo Terminals (depending on what the calling application is doing).

**Comment by AstraLuma** [comment] 2017-03-18 20:38
@mitnk There _is_ a bug on Mac. I'm guessing some kind of race condition where the forked child hasn't gotten any CPU time yet, and is therefore not set up in some way.

Or maybe a race condition where fork-exec and `ls` is executed in a single time slice? Seems unlikely, but is possible.

**Comment by ghost** [comment] 2017-03-18 20:49
then we can either do it only when we use pipes or do it always except when passing sys.stdin/sys.stdout, ProcessGroup holds this info.

**Comment by AstraLuma** [comment] 2017-03-18 21:01
`Process` gets handed a file-like object, and there's all kinds of concrete Python types that look like files, and lots of different kind of things that get wrapped up in the same Python type (like what `Pipe` does, and what will likely happen with psuedo terminals). Oh, and it's not explicitly supported, but if you hand it a file descriptor (ie, an integer), it'll work. And we wouldn't have a prayer of guessing what kind of thing it is.

`ProcessGroup` doesn't get told at all about how the processes are connected (nor does it really care).

**Comment by AstraLuma** [comment] 2017-03-18 21:08
Hm, on further thought it might be that `ls` exits too quickly. Otherwise, `test_pgid()` would fail.

EDIT: Also, setting up the rest of the pipeline doesn't fail, so the process group still exists at that point.

**Comment by AstraLuma** [comment] 2017-03-18 21:15
@mitnk Should be fixed now. The problem with `pgid` failing is #11, which I'm not sure what's the right way to fix. But Mac should be working again and there's now a test for this.

**Comment by mitnk** [comment] 2017-03-19 01:24
> You need to close your copies of the Pipe sides after the processes have started.
> (slug doesn't handle this in cases where, say, you're passing a PTY to 3 programs or whatever.)

Then what's the points we introduce slug if it doesn't handle this?

**Comment by mitnk** [comment] 2017-03-19 01:24
Now it stuck both on linux and mac.

**Comment by mitnk** [comment] 2017-03-19 01:33
Also maybe you could update the readme so that others can know how to run it (include `from * import *` in code sample), to help on testing if interested. Also put something to describe what slug want to achieve?

**Comment by mitnk** [comment] 2017-03-19 01:37
Even better, I think slug should hide the internal pipes from using? for example, the code here
```
from slug import Process, ProcessGroup, Pipe

with ProcessGroup() as pg:
  pipe = Pipe()
  spam = pg.add(Process(['ls', 'lh'], stdout=pipe.side_in))
  eggs = pg.add(Process(['grep', 'foo'], stdin=pipe.side_out))
pg.start()
pg.join()
```
should be simplified to something like this?
```
from slug import ProcessGroup
pg = ProcessGroup(['ls', '-lh'], ['grep', 'foo'])
pg.start()
```

**Comment by AstraLuma** [comment] 2017-03-20 03:56
That would be an Opinion about How To Do Things, and expanding the syntax for the features that Processes support would make the call complicated. (What's the initial stdin/out/err? Environment variables? Do you want any kind of plumbing between processes? etc) As to why it can't be closed automatically, in summary: `Process` doesn't have enough information to know what exactly it is nor does it know the greater context of the usage.

Pipe closures is part of the the pipe state machine, and are therefore an exposed part of the abstraction. Or: Slug doesn't necessarily make it easy, just makes it possible to do in a cross-platform way without loosing your mind. Slug is an object-oriented interface to the POSIX process and piping model implemented for multiple platforms. If you want easy, try subprocess or sh or several other PyPI packages. Or, you know, xonsh. Slug is written to make these tools easier to write. It is verbose on purpose because it makes it clear what the low-level operations are and how the code is orchestrating the kernel objects.

Pragmatically, I already wrote code on the xonsh side to deal with this. It was, in fact, much, much easier to write than the actual parsing of the redirects in the command.

**Comment by mitnk** [comment] 2017-03-20 04:13
Nice to hear it simplified the xonsh side :)

If the pipes created here is needed outside of `ProcessGroup`, it makes sense to show their explicit creation (thou it also could be accessing with `pg.last_pipe` or something?)

My previous proposed demo code was assuming the pipes will not be used outside. I guess I'm wrong here? (And for environment bariables or other needed stuff, they could be passed along when creating `ProcessGroup` object).

**Closed as completed** 2017-04-28 23:24 UTC
Labels: bug
